apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: {{ .Values.service.portname }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: LoadBalancer
