variable "application_gateway_name" {}
variable "resource_group_name" {}
variable "location" {}
variable "sku_name" {}
variable "sku_tier" {}
variable "sku_capacity" {}
variable "gateway_ip_configuration_name" {}
variable "subnet_id" {}
variable "frontend_ip_configuration_name" {}
variable "public_ip_address_id" {}
variable "frontend_port_name" {}
variable "frontend_port_port" {}
variable "backend_address_pool_name" {}
variable "backend_http_settings_name" {}
variable "cookie_based_affinity" {}
variable "backend_http_settings_port" {}
variable "backend_http_settings_protocol" {}
variable "backend_http_settings_request_timeout" {}
variable "http_listener_name" {}
variable "http_listener_frontend_ip_configuration_name" {}
variable "http_listener_frontend_port_name" {}
variable "http_listener_protocol" {}
variable "request_routing_rule_name" {}
variable "request_routing_rule_rule_type" {}
variable "request_routing_rule_priority" {}
variable "request_routing_rule_http_listener_name" {}
variable "request_routing_rule_backend_address_pool_name" {}
variable "request_routing_rule_backend_http_settings_name" {}
