variable "admin_username" {}
variable "admin_password" {}
variable "disable_password_authentication" {}
variable "name" {}
variable "linuxVM_nic_id" {}
variable "resource_group_name" {}
variable "size" {}
variable "caching" {}
variable "storage_account_type" {}
variable "publisher" {}
variable "offer" {}
variable "sku" {}
variable "version_vm" {}
variable "resource_group_location" {}
variable "nic_name" {}
variable "nic_name_ip" {}
variable "nic_subnet_id" {}
variable "nic_ip_allocation" {}
