variable "key_vault_name" {}
variable "resource_group_name" {}
variable "location" {}
variable "tenant_id" {}
variable "soft_delete_retention_days" {}
variable "sku_name" {}
variable "object_id" {}
variable "key_permissions" {}
variable "secret_permissions" {}
variable "certificate_permissions" {}
variable "secret_names" {}
variable "secret_values" {}
variable "key_names" {}
variable "key_types" {}
variable "key_sizes" {}
variable "key_opts" {}
variable "time_before_expiry" {}
variable "expire_after" {}
variable "notify_before_expiry" {}
variable "enabled_for_disk_encryption" {}
variable "purge_protection_enabled" {}
variable "user_assigned_identity_principal_id" {}
variable "aks_secret_provider_id" {}
