apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "759cb4ea-709b-4827-bd17-8053058653c7"
    keyvaultName: "keywithhelmcluster"
    objects: |
      array:
        - |
          objectName: "mysecret"
          objectType: "secret"
          objectVersion: ""
    tenantId: "e994072b-523e-4bfe-86e2-442c5e10b244"
secretObjects:
  - data:
      - objectName: "mysecret"
        key: "mysecret"
    secretName: aks-secret-provider-secret
    type: Opaque
