variable "name" {}
variable "resource_group_location" {}
variable "resource_group_name" {}
variable "security_name" {}
variable "security_priority" {}
variable "security_direction" {}
variable "security_access" {}
variable "security_protocol" {}
variable "security_source_port_range" {}
variable "security_destination_port_range" {}
variable "security_source_address_prefix" {}
variable "security_destination_address_prefix" {}