apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: "8c1e0053-4320-4bc5-ae1c-d34cfc79cf7d"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "myKeyVault-109988" # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: webserver-config
          objectType: secret # object types: secret, key, or cert
        - |
          objectName: webserver-properties
          objectType: secret
    tenantId: "e994072b-523e-4bfe-86e2-442c5e10b244" # The tenant ID of the key vault
---
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline-user-msi
spec:
  containers:
  - name: busybox
    image: registry.k8s.io/e2e-test-images/busybox:1.29-1
    command:
    - "/bin/sleep"
    - "10000"
    volumeMounts:
    - mountPath: "/app/config.conf"
      name: webserver-configuration
      subPath: webserver-config
      readOnly: true
    - mountPath: "/app/application.properties"
      name: webserver-configuration
      subPath: webserver-properties
      readOnly: true
  volumes:
  - name: webserver-configuration
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-kvname-user-msi"