variable "cluster_name" {}
variable "resource_group_name" {}
variable "location" {}
variable "dns_prefix" {}
variable "node_pool_name" {}
variable "node_count" {}
variable "vm_size" {}
variable "os_disk_size_gb" {}
variable "vnet_subnet_id" {}
variable "network_plugin" {}
variable "identity_type" {}
variable "local_file_name" {}
variable "secret_rotation_enabled" {}
