apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: ecommerce
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "551291e0-6eb9-4cf6-9eb2-8e76612b9fde"
    keyvaultName: "myKeyVault-107488"
    objects: |
      array:
        - |
          objectName: NEXT-PUBLIC-CLERK-PUBLISHABLE-KEY
          objectType: secret
        - |
          objectName: CLERK-SECRET-KEY
          objectType: secret
        - |
          objectName: NEXT-PUBLIC-CLERK-SIGN-IN-URL
          objectType: secret
        - |
          objectName: NEXT-PUBLIC-CLERK-AFTER-SIGN-IN-URL
          objectType: secret
        - |
          objectName: DATABASE-URL
          objectType: secret
        - |
          objectName: NEXT-PUBLIC-CLOUDINARY-CLOUD-NAME
          objectType: secret
        - |
          objectName: NEXT-PUBLIC-CLERK-SIGN-UP-URL
          objectType: secret
        - |
          objectName: NEXT-PUBLIC-CLERK-AFTER-SIGN-UP-URL
          objectType: secret
        - |
          objectName: CLOUDINARY-PRESET-NAME
          objectType: secret
        - |
          objectName: FRONTEND-STORE-URL
          objectType: secret
        - |
          objectName: STRIPE-API-KEY
          objectType: secret
        - |
          objectName: STRIPE-WEBHOOK-SECRET
          objectType: secret
        - |
          objectName: NEXT-PUBLIC-API-URL
          objectType: secret
        - |
          objectName: REACT-EDITOR
          objectType: secret
        - |
          objectName: BILLBOARD-ID
          objectType: secret
    tenantId: "e994072b-523e-4bfe-86e2-442c5e10b244"
  secretObjects:
    - secretName: azure-keyvault-secrets
      type: Opaque
      data:
        - key: NEXT-PUBLIC-CLERK-PUBLISHABLE-KEY
          objectName: NEXT-PUBLIC-CLERK-PUBLISHABLE-KEY
        - key: CLERK-SECRET-KEY
          objectName: CLERK-SECRET-KEY
        - key: NEXT-PUBLIC-CLERK-SIGN-IN-URL
          objectName: NEXT-PUBLIC-CLERK-SIGN-IN-URL
        - key: NEXT-PUBLIC-CLERK-AFTER-SIGN-IN-URL
          objectName: NEXT-PUBLIC-CLERK-AFTER-SIGN-IN-URL
        - key: DATABASE-URL
          objectName: DATABASE-URL
        - key: NEXT-PUBLIC-CLOUDINARY-CLOUD-NAME
          objectName: NEXT-PUBLIC-CLOUDINARY-CLOUD-NAME
        - key: NEXT-PUBLIC-CLERK-SIGN-UP-URL
          objectName: NEXT-PUBLIC-CLERK-SIGN-UP-URL
        - key: NEXT-PUBLIC-CLERK-AFTER-SIGN-UP-URL
          objectName: NEXT-PUBLIC-CLERK-AFTER-SIGN-UP-URL
        - key: CLOUDINARY-PRESET-NAME
          objectName: CLOUDINARY-PRESET-NAME
        - key: FRONTEND-STORE-URL
          objectName: FRONTEND-STORE-URL
        - key: STRIPE-API-KEY
          objectName: STRIPE-API-KEY
        - key: STRIPE-WEBHOOK-SECRET
          objectName: STRIPE-WEBHOOK-SECRET
        - key: NEXT-PUBLIC-API-URL
          objectName: NEXT-PUBLIC-API-URL
        - key: REACT-EDITOR
          objectName: REACT-EDITOR
        - key: BILLBOARD-ID
          objectName: BILLBOARD-ID